version: "3.8"

services:
  backend:
    build: ./backend
    container_name: notes-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=pass123
      - DB_NAME=focus_notes
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: notes-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: notes-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: focus_notes
    ports:
      - "3309:3309"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
